# Generated by Django 3.1.7 on 2021-04-04 20:48

from django.db import migrations, models
import ticket.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', validators=[ticket.validators.validate_file_size], verbose_name='فایل ضمیمه پیام'),
        ),
    ]
