# Generated by Django 3.1.7 on 2021-04-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20210405_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='slug',
        ),
    ]
