# Generated by Django 3.1.7 on 2021-04-09 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0003_remove_ticket_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketdetail',
            options={'verbose_name': 'جزئیات تیکت', 'verbose_name_plural': 'جزئیات تیکت ها'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='سازنده تیکت'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_detail', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده پیام'),
        ),
    ]
